### PR TITLE
Add travis support

### PR DESCRIPTION
**Pull request by lol768**
Will try and build automatically on commit/PR.

Currently unsure whether the `libsodium` stuff will work. May need some advice on how to get it to compile

### CODE REVIEW

**Comment by lol768** [comment]
Additional issue: `libsodium-dev` isn't available because staying up to date on Ubuntu LTS releases is apparently too hard travis-ci/travis-ci#5821

**Comment by jkcclemens** [comment]
[Here](https://github.com/jkcclemens/lalafell_bot/blob/dev/.travis.yml#L21) is how I handle `libsodium` on another project.

**Comment by lol768** [comment]
>$HOME/libsodium should be cached to prevent rebuilding it every time.

:heavy_check_mark:

**Comment by lol768** [comment]
Build to watch: https://travis-ci.org/lol768/paste/builds/370236471

**Pull request merged**
