### PR TITLE
chore: update favicon

### PR DESCRIPTION
**Pull request by AKPWebDesign**
favicons are fun

### CODE REVIEW

**Comment by AKPWebDesign** [comment]
Oh, I guess I should note that this icon is based on a Twemoji, which I think means it's licensed [CC-BY 4.0](https://github.com/twitter/twemoji/blob/gh-pages/LICENSE-GRAPHICS).

**Comment by jkcclemens** [comment]
The script should not be in the static directory. Files in that directory are served at `/static/` verbatim.

**Comment by jkcclemens** [comment]
`only_lines.svg` should be `favicon.svg`

**Comment by AKPWebDesign** [comment]
I think that should resolve those issues.

**Comment by lol768** [comment]
>Oh, I guess I should note that this icon is based on a Twemoji, which I think means it's licensed CC-BY 4.0.

Where are we attributing

**Comment by jkcclemens** [comment]
why\
pls

Creative Commons' website sucks and doesn't let me copy out of the tooltip.

Anyway, leave it to @lol768 to kill our fun and point out that we should follow the license. Could add a "Licenses" or "Credits" or similar link to the footer?

**Pull request merged**
